---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: prod
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"

spec:
  releaseName: podinfo
  chart:
    git: git@github.com:praveenchandran/gitops-helm-workshop
    ref: master
    path: cluster/charts/podinfo
  values:
    image:
      repository: 765715887385.dkr.ecr.eu-central-1.amazonaws.com/test/podinfo
      tag: 2.6.7
    service:
      enabled: false
      type: ClusterIP
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
        nginx.ingress.kubernetes.io/configuration-snippet: |
          proxy_set_header l5d-dst-override $service_name.$namespace.svc.cluster.local:9898;
          proxy_hide_header l5d-remote-ip;
          proxy_hide_header l5d-server-id;
      path: /
      hosts:
      - a06825364db2911e9a70f0a071e2085d-1243135011.eu-central-1.elb.amazonaws.com
